### ISSUE TITLE
forecast attribute is deprecated

### ISSUE THREAD

**Issue by DTekNOdev** [toringer/home-assistant-metnowcast#13]
HA 2023.9.0 says:

The metnowcast integration is using deprecated forecast
This stops working in version 2024.3.0. Please address before upgrading.
The integration metnowcast is using the deprecated forecast attribute.

Please report it to the custom integration author..

**Comment by toringer** [comment]
Fixed in v2.3.1

**Comment by jm-cook** [comment]
The response to get_forecasts includes some datetime objects which is tricky to deal with.

See https://github.com/toringer/home-assistant-metnowcast/issues/15

See also https://community.home-assistant.io/t/stuck-with-template-and-get-forecasts/714976
