### ISSUE TITLE
Wind speed in m/s has wrong decimal place

### ISSUE THREAD

**Issue by palengh** [toringer/home-assistant-metnowcast#8]
When selecting m/s for wind speed, The state needs to be multiplisere by 10 to be correct. Eg. At 00:28, July 18, wind speed at Kråkerøy kirke is displaying 1.09 m/s, whoch is incorrect.

**Comment by toringer** [comment]
Added native units for wind speed and precipitation on the entity. Home Assistant will convert correctly now.
PS! You must select your preferred units on the entity.
