### ISSUE TITLE
Error to be reported

### ISSUE THREAD

**Issue by strelniece** [toringer/home-assistant-metnowcast#9]
Hi, this just showed up in my log

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:198
Integration: Weather (documentation, issues)
First occurred: 15:45:43 (1 occurrences)
Last logged: 15:45:43

custom_components.metnowcast.weather::NowcastWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by toringer** [comment]
Thanks for letting me know 👍 
Fixed in version 2.1.0
